const SIDEBAR__TOGGLE = "SIDEBAR__TOGGLE";
const SHOW__SENTBOX = "SHOW__SENTBOX";
const HIDE__SENTBOX = "HIDE__SENTBOX";

const CREATE__AN__ACCOUNT = "CREATE__AN__ACCOUNT";
const CREATE__AN__ACCOUNT__REQUESTED = "CREATE__AN__ACCOUNT__REQUESTED";
const CREATE__AN__ACCOUNT__FAILURE = "CREATE__AN__ACCOUNT__FAILURE";
const CREATE__AN__ACCOUNT__SUCCESS = "CREATE__AN__ACCOUNT__SUCCESS";

const SHOW__LOADER = "SHOW__LOADER";
const HIDE__LOADER = "HIDE__LOADER";

export {
  SIDEBAR__TOGGLE,
  SHOW__SENTBOX,
  HIDE__SENTBOX,
  CREATE__AN__ACCOUNT,
  CREATE__AN__ACCOUNT__REQUESTED,
  CREATE__AN__ACCOUNT__FAILURE,
  CREATE__AN__ACCOUNT__SUCCESS,
  SHOW__LOADER,
  HIDE__LOADER,
};
