const FETCH__EMAILS = "FETCH__EMAILS";
const FETCH__EMAILS__REQUESTED = "FETCH__EMAILS__REQUESTED";
const FETCH__EMAILS__FAILURE = "FETCH__EMAILS__FAILURE";
const FETCH__EMAILS__SUCCESS = "FETCH__EMAILS__SUCCESS";

const SENT__EMAIL = "SENT__EMAIL";
const SENT__EMAIL__REQUESTED = "SENT__EMAIL__REQUESTED";
const SENT__EMAIL__FAILURE = "SENT__EMAIL__FAILURE";
const SENT__EMAIL__SUCCESS = "SENT__EMAIL__SUCCESS";

const GET__EMAIL__DETAIL = "GET__EMAIL__DETAIL";
const GET__EMAIL__DETAIL__REQUESTED = "GET__EMAIL__DETAIL__REQUESTED";
const GET__EMAIL__DETAIL__FAILURE = "GET__EMAIL__DETAIL__FAILURE";
const GET__EMAIL__DETAIL__SUCCESS = "GET__EMAIL__DETAIL__SUCCESS";

export {
  FETCH__EMAILS,
  FETCH__EMAILS__REQUESTED,
  FETCH__EMAILS__FAILURE,
  FETCH__EMAILS__SUCCESS,
  SENT__EMAIL,
  SENT__EMAIL__REQUESTED,
  SENT__EMAIL__FAILURE,
  SENT__EMAIL__SUCCESS,
  GET__EMAIL__DETAIL,
  GET__EMAIL__DETAIL__REQUESTED,
  GET__EMAIL__DETAIL__FAILURE,
  GET__EMAIL__DETAIL__SUCCESS,
};
