const SENT__EMAIL = "SENT__EMAIL";
const PRIMARY__SELECTED = "PRIMARY__SELECTED";
const SOCIAL__SELECTED = "SOCIAL__SELECTED";
const PROMOTION__SELECTED = "PROMOTION__SELECTED";
const DELETE__EMAIL = "DELETE__EMAIL";

export {
  SENT__EMAIL,
  PRIMARY__SELECTED,
  SOCIAL__SELECTED,
  PROMOTION__SELECTED,
  DELETE__EMAIL,
};
