const FETCH__EMAILS = "FETCH__EMAILS";
const FETCH__EMAILS__REQUESTED = "FETCH__EMAILS__REQUESTED";
const FETCH__EMAILS__FAILURE = "FETCH__EMAILS__FAILURE";
const FETCH__EMAILS__SUCCESS = "FETCH__EMAILS__SUCCESS";

const SENT__EMAIL = "SENT__EMAIL";
const SENT__EMAIL__REQUESTED = "SENT__EMAIL__REQUESTED";
const SENT__EMAIL__FAILURE = "SENT__EMAIL__FAILURE";
const SENT__EMAIL__SUCCESS = "SENT__EMAIL__SUCCESS";

const PRIMARY__SELECTED = "PRIMARY__SELECTED";
const SOCIAL__SELECTED = "SOCIAL__SELECTED";
const PROMOTION__SELECTED = "PROMOTION__SELECTED";
const DELETE__EMAIL = "DELETE__EMAIL";
const GET__ID = "GET__ID";
const SET__ID = "SET__ID";

export {
  FETCH__EMAILS,
  FETCH__EMAILS__REQUESTED,
  FETCH__EMAILS__FAILURE,
  FETCH__EMAILS__SUCCESS,
  SENT__EMAIL,
  SENT__EMAIL__REQUESTED,
  SENT__EMAIL__FAILURE,
  SENT__EMAIL__SUCCESS,
  PRIMARY__SELECTED,
  SOCIAL__SELECTED,
  PROMOTION__SELECTED,
  DELETE__EMAIL,
  GET__ID,
  SET__ID,
};
