const FETCH__USERS = "FETCH__USERS";
const FETCH__USERS__REQUESTED = "FETCH__USERS__REQUESTED";
const FETCH__USERS__FAILURE = "FETCH__USERS__FAILURE";
const FETCH__USERS__SUCCESS = "FETCH__USERS__SUCCESS";
const SET__USERS = "SET__USERS";

const USER__LOGIN = "USER__LOGIN";
const USER__LOGOUT = "USER__LOGOUT";
const USER__PROFILE__UPDATE = "USER__PROFILE__UPDATE";
const GET__USERS = "GET__USERS";
const USER__LOGIN__REQUESTED = "USER__LOGIN__REQUESTED";
const USER__LOGIN__FAILURE = "USER__LOGIN__FALIURE";

const USER__LOGIN__SUCCESS = "USER__LOGIN__SUCCESS";

export {
  FETCH__USERS,
  SET__USERS,
  USER__LOGIN,
  USER__LOGOUT,
  USER__PROFILE__UPDATE,
  GET__USERS,
  USER__LOGIN__REQUESTED,
  USER__LOGIN__FAILURE,
  USER__LOGIN__SUCCESS,
  FETCH__USERS__REQUESTED,
  FETCH__USERS__FAILURE,
  FETCH__USERS__SUCCESS,
};
