const USER__LOGIN = "USER__LOGIN";
const USER__LOGOUT = "USER__LOGOUT";
const USER__PROFILE__UPDATE = "USER__PROFILE__UPDATE";
const SENT__EMAIL = "SENT__EMAIL";

export { USER__LOGIN, USER__LOGOUT, USER__PROFILE__UPDATE, SENT__EMAIL };
